/*
SQLyog Ultimate v9.51 
MySQL - 5.5.8 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

create table `navigation` (
	`id` int (11),
	`parent` int (11),
	`type` varchar (60),
	`title` varchar (765),
	`link` varchar (765),
	`login` int (1),
	`not_login` int (1),
	`before` blob ,
	`after` blob ,
	`order` Decimal (13),
	`created` int (11),
	`createby` varchar (765),
	`updated` int (11),
	`updateby` varchar (765),
	`status` int (1)
); 
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('2','0','top-navigation','Giới thiệu về Plan No.','site:intro/intro/index','1','1','','','0.00','1324027971','nnquangit','1330675087','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('3','0','top-navigation','Tin tức','site:news/news/index','0','0','','','0.00','1324028467','nnquangit','1324028467','nnquangit','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('4','0','top-navigation','Chia sẻ kinh nghiệm','site:post/post/index','0','0','','','0.00','1324028721','nnquangit','1324970674','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('5','0','top-navigation','Bạn đọc viết','site:blog/blog/index','0','0','','','0.00','1324028836','nnquangit','1324028836','nnquangit','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('6','0','top-navigation','Thanh toán','site:thanh-toan','0','0','','','0.00','1324028849','nnquangit','1324028849','nnquangit','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('7','0','top-navigation','Thông báo','site:notice/notice/index','0','0','','','0.00','1324028862','nnquangit','1324028862','nnquangit','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('8','0','top-navigation','Liên hệ','site:contact/contact/index','0','0','','','0.00','1324028876','nnquangit','1326514797','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('9','0','left-navigation','Quản lý thông tin cá nhân','site:user/user/profile','1','0','','','3.00','1324028935','nnquangit','1329446508','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('10','9','left-navigation','Thông tin cá nhân','site:user/user/profile','0','0','','','1.00','1324029080','nnquangit','1326699284','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('11','9','left-navigation','Quan hệ gia đình','site:family/family/index','0','0','','','3.00','1324029070','nnquangit','1326677806','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('12','9','left-navigation','Danh bạ bạn bè','site:friends/friends/index','0','0','','','4.00','1324029062','nnquangit','1326677787','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('13','9','left-navigation','Học tập và nghề nghiệp','site:biography/biography/index','0','0','','','5.00','1324029125','nnquangit','1326677858','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('14','9','left-navigation','Nguyện vọng và mục tiêu','site:user/user/wish','0','0','','','6.00','1324029157','nnquangit','1326679162','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('15','9','left-navigation','Sở thích cá nhân','site:user/user/preference','0','0','','','7.00','1324029198','nnquangit','1326679205','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('16','18','left-navigation','Tổng hợp kế hoạch','site:schedule/schedule/category','0','0','','','3.00','1324029241','nnquangit','1330485112','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('17','0','left-navigation','Quản lý đầu tư và tài chính','site:investement/investement/index','1','0','','','5.00','1324029267','nnquangit','1329446662','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('18','0','left-navigation','Quản lý thời gian, công việc','site:schedule/schedule/index','1','0','','','6.00','1324029300','nnquangit','1329446733','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('19','0','left-navigation','Quản lý thu - chi','site:income/income/index','1','0','','','7.00','1324029353','nnquangit','1329446787','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('20','19','left-navigation','Các khoản phải thu','site:income/income/index/','0','0','','','0.00','1324029475','nnquangit','1324029475','nnquangit','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('21','19','left-navigation','Các khoản phải chi','site:income/income_payment/index','0','0','','','0.00','1324029495','nnquangit','1326710488','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('22','19','left-navigation','Báo cáo thu chi','site:income/income/report','0','0','','','0.00','1324029523','nnquangit','1331894982','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('23','19','left-navigation','Tổng hợp thu chi','site:income/income/synthesis','0','0','','','0.00','1324029546','nnquangit','1331895026','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('24','19','left-navigation','Tích lũy hằng năm','site:accumulate/accumulate','0','0','','','0.00','1324029586','nnquangit','1331965274','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('25','0','left-navigation','Album cá nhân','site:gallery/gallery/index','1','0','','','8.00','1324029619','nnquangit','1329446840','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('26','0','left-navigation','Tổng hợp file đính kèm','site:resourcesmanager/resourcesmanager','1','0','','','9.00','1324029663','nnquangit','1330671682','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('27','0','left-navigation','Tin tức tổng hợp','site:news/news/index','1','1','','','10.00','1325068818','admin','1329446924','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('28','0','left-navigation','Chia sẻ kinh nghiệm','site:post/post/index','1','1','','','11.00','1324030336','nnquangit','1332219221','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('29','28','left-navigation','Tình ban -  tinh yêu','site:post/post/category/tinh-ban-tinh-yeu','0','0','','','0.00','1324873485','admin','1324873485','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('30','28','left-navigation','Nghề nghiệp','site:post/post/category/nghe-nghiep','0','0','','','0.00','1324873554','admin','1324873554','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('31','28','left-navigation','Học làm giàu','site:post/post/category/hoc-lam-giau','0','0','','','0.00','1324030433','nnquangit','1324030433','nnquangit','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('32','28','left-navigation','Kinh nghiệm sống','site:post/post/category/kinh-nghiem-song','0','0','','','0.00','1324030486','nnquangit','1324030486','nnquangit','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('33','28','left-navigation','Gia đình','site:post/post/category/gia-dinh','0','0','','','0.00','1324030510','nnquangit','1324030510','nnquangit','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('34','28','left-navigation','Kỹ năng công việc','site:post/post/category/ky-nang-cong-viec','0','0','','','0.00','1324030536','nnquangit','1324030536','nnquangit','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('35','28','left-navigation','Chuyện thành công','site:post/post/category/chuyen-thanh-cong','0','0','','','0.00','1324030556','nnquangit','1324030556','nnquangit','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('36','0','left-navigation','Bạn đọc viết','site:blog/blog/index','1','1','','','12.00','1324030588','nnquangit','1329447044','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('37','36','left-navigation','Khoa học','site:blog/blog/category/khoa-hoc','0','0','','','8.00','1324030633','nnquangit','1326680083','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('38','36','left-navigation','Đời sống','site:blog/blog/category/doi-song','0','0','','','7.00','1324030658','nnquangit','1326680070','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('39','36','left-navigation','Pháp luật','site:blog/blog/category/phap-luat','0','0','','','6.00','1324030681','nnquangit','1326680058','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('40','36','left-navigation','Xã hội','site:blog/blog/category/xa-hoi','0','0','','','5.00','1324030705','nnquangit','1326680045','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('41','36','left-navigation','Kinh doanh','site:blog/blog/category/kinh-doanh','0','0','','','4.00','1324030745','nnquangit','1326680033','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('42','36','left-navigation','Thể thao','site:blog/blog/category/the-thao','0','0','','','3.00','1324030771','nnquangit','1326680016','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('43','36','left-navigation','Văn hóa','site:blog/blog/category/van-hoa','0','0','','','2.00','1324030795','nnquangit','1326679314','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('44','36','left-navigation','Thế giới','site:blog/blog/category/the-gioi','0','0','','','1.00','1324030820','nnquangit','1326679292','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('45','36','left-navigation','Tâm sự','site:blog/blog/category/tam-su','0','0','','','9.00','1324030838','nnquangit','1326680098','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('46','0','left-navigation','Thùng rác','site:recycle/recycle','1','0','','','13.00','1324030867','nnquangit','1330930029','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('47','46','left-navigation','Tin rác','site:recycle/recycle','1','0','','','0.00','1324030881','nnquangit','1330741587','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('48','46','left-navigation','Dung lượng','','0','0','','','0.00','1324030900','nnquangit','1324030900','nnquangit','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('49','0','left-navigation','Giới thiệu về Planno','site:intro/intro/index','1','0','','','14.00','1324030924','nnquangit','1329449223','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('50','0','left-navigation','Thông tin cần biết','site:exchangerate/exchangerate/index','1','1','','','12.10','1324030945','nnquangit','1332384577','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('51','0','left-navigation','Bảng giá dịch vụ','site:bang-gia-dich-vu','1','1','','','16.00','1324030968','nnquangit','1329447325','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('52','0','left-navigation','Hướng dẫn sử dụng','site:huong-dan-su-dung','1','0','','','17.00','1324030999','nnquangit','1329449242','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('53','0','left-navigation','Thông báo Planno','site:notice/notice/index','1','1','','','18.00','1324031028','nnquangit','1329447591','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('54','0','left-navigation','Hỗ trợ trực tuyến','site:ho-tro-truc-tuyen','0','1','','','21.00','1324031052','nnquangit','1331095174','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('55','9','left-navigation','Thông tin tài khoản','site:user/user/account','0','0','','','2.00','1326520532','admin','1326699675','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('56','9','left-navigation','Nhật ký online','site:diary/diary','0','0','','','8.00','1326520798','admin','1326679220','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('58','18','left-navigation','Lập kế hoạch thực hiện','site:schedule/schedule/index','0','0','','','1.00','1326700587','admin','1326765950','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('63','18','left-navigation','Lịch làm việc trong tháng','site:schedule/schedule/calendar','0','0','','','2.00','1326766116','admin','1332020248','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('66','18','left-navigation','Sổ tay cuộc sống','site:notebook/notebook/category/cong-viec-hang-ngay/1','0','0','','','6.00','1326766237','admin','1331642441','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('67','0','left-navigation','Đăng ký sử dụng','site:user/user/register','0','1','','','1.00','1329376778','admin','1329446395','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('68','0','left-navigation','Đăng nhập','site:user/user/login','0','1','','','2.00','1329376856','admin','1329453751','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('69','0','left-navigation','Thanh toán','site:thanh-toan','0','1','','','19.00','1329376945','admin','1329448580','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('70','0','left-navigation','Liên hệ','site:contact/contact/index','0','1','','','20.00','1329376993','admin','1329447650','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('71','0','left-navigation','Quản lý tài sản','site:asset/asset/index','1','0','','','4.00','1329445671','admin','1329446633','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('72','0','left-navigation','Sản phẩm & dịch vụ','','1','0','','','15.00','1329447245','admin','1329449317','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('73','50','left-navigation','Giá vàng','','0','0','','','0.00','1329448017','admin','1329448017','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('74','50','left-navigation','Tỷ giá ngoại tệ','','0','0','','','0.00','1329448059','admin','1329448059','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('75','50','left-navigation','Thời tiết','site:exchangerate/exchangerate','0','0','','','0.00','1329448090','admin','1332387296','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('76','0','left-navigation','Hướng dẫn sử dụng','site:huong-dan-su-dung','0','1','','','2.10','1329449056','admin','1329449160','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('77','0','left-navigation','Giới thiệu Plan No','site:gioi-thieu','0','1','','','2.20','1329449137','admin','1329453727','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('78','18','left-navigation','Ghi nhớ nhanh','site:quicknotes/quicknotes','1','0','','','5.00','1330484796','admin','1330748858','admin','1');
insert into `navigation` (`id`, `parent`, `type`, `title`, `link`, `login`, `not_login`, `before`, `after`, `order`, `created`, `createby`, `updated`, `updateby`, `status`) values('79','18','left-navigation','Lịch học, làm việc tuần','site:','0','0','','','4.00','1330484866','admin','1330485167','admin','1');
